spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/advertisement-board
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: changelog/main-changelog.xml
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
advertisement-board:
  authorization:
    secret: "123"
    expiration: 86400000
  contacts: '{
    phone: "+7 (920) 987-12-23",
    email: "example@gmail.com"
  }'