spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/advertisement-board
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: changelog/main-changelog.xml

